# questions.py

global age_category

questions = {
    '0 a 1 ano': {
        "Socialização": [
            "Observa uma pessoa movimentando-se em seu campo visual.",
            "Sorri em resposta à atenção do adulto.",
            "Vocaliza em resposta à atenção.",
            "Olha para sua própria mão, sorrindo ou vocalizando.",
            "Responde a seu círculo familiar, sorrindo, vocalizando ou parando de chorar.",
            "Sorri em resposta à expressão facial dos outros.",
            "Sorri e vocaliza ao ver sua imagem no espelho.",
            "Acaricia ou toca no rosto de adultos (puxa cabelo, nariz, óculos, etc.).",
            "Estende a mão em direção a um objeto oferecido.",
            "Estende os braços em direção a pessoas familiares.",
            "Estende a mão e toca sua imagem refletida no espelho.",
            "Segura e examina por 1 minuto um objeto que lhe foi dado.",
            "Sacode ou aperta um objeto colocado em sua mão, produzindo sons involuntários.",
            "Brinca sozinho por 10 minutos.",
            "Procura contato visual quando alguém lhe dá atenção por 2 a 3 minutos.",
            "Brinca sozinho sem reclamar por 15 a 20 minutos, próximo de um adulto.",
            "Vocaliza para obter atenção.",
            "Imita adulto em brincadeiras de esconde-esconde.",
            "Bate palmas, imitando um adulto.",
            "Acena a mão, imitando um adulto.",
            "Ergue os braços para expressar “grande”, imitando um adulto.",
            "Oferece algo, mas nem sempre entrega.",
            "Abraça, acaricia e beija familiares.",
            "Responde ao próprio nome, olhando ou estendendo o braço para ser pego.",
            "Aperta ou sacode um brinquedo para produzir sons, em imitação.",
            "Manipula brinquedo ou objeto.",
            "Estende um brinquedo ou objeto a um adulto e o entrega.",
            "Imita movimentos de outras crianças ao brincar."
        ],
        "Linguagem": [
            "Repete sons emitidos por outras pessoas.",
            "Repete a mesma sílaba 2 a 3 vezes.",
            "Responde a gestos com gestos.",
            "Obedece a uma ordem simples, quando acompanhada de gestos indicativos.",
            "Interrompe a atividade quando lhe dizem \"Não\" 75% das vezes.",
            "Responde a perguntas simples com respostas não verbais.",
            "Combina 2 sílabas diferentes quando tenta verbalizar.",
            "Imita padrões de entonação da voz de outras pessoas.",
            "Usa uma palavra funcionalmente para indicar objetos ou pessoas.",
            "Vocaliza em resposta à fala de outras pessoas."
        ],
        "Cognição": [
            "Remove um pano do rosto que obscureça sua visão.",
            "Procura com o olhar um objeto que foi tirado de seu campo visual.",
            "Remove um objeto de um recipiente colocando a mão dentro do mesmo.",
            "Coloca um objeto em um recipiente imitando um adulto.",
            "Coloca um objeto em um recipiente quando recebe instruções.",
            "Balança um brinquedo que produz som, pendurado em um barbante.",
            "Coloca três objetos em um recipiente e o esvazia.",
            "Transfere um objeto de uma mão à outra para apanhar outro objeto.",
            "Deixa cair e apanha um brinquedo.",
            "Descobre um objeto escondido sob um recipiente.",
            "Empurra 3 blocos como se fosse um comboio.",
            "Remove um círculo de uma prancha, por imitação.",
            "Coloca um pino redondo em uma prancha de pinos, quando solicitado.",
            "Executa gestos simples quando requisitado."
        ],
        "Auto Cuidado": [
            "Suga e deglute líquidos.",
            "Toma mingau / sopinha.",
            "Estende as mãos em direção a mamadeira, tentando pegá-la.",
            "Come alimentos liquidificados dados pelos pais.",
            "Segura a mamadeira sem ajuda enquanto bebe.",
            "Leva a mamadeira até a boca ou a recusa, empurrando-a.",
            "Come alimentos amassados dados pelos pais.",
            "Bebe em uma caneca, segurada pelos pais.",
            "Come alimentos semissólidos dados pelos pais.",
            "Alimenta-se sozinho usando os dedos.",
            "Segura a caneca com ambas as mãos e bebe.",
            "Leva a colher cheia de comida até a boca com ajuda.",
            "Estica braços e pernas ao ser vestido."
        ],
        "Desenvolvimento Motor": [
            "Alcança um objeto colocado à sua frente (15 a 20 cm).",
            "Apanha um objeto colocado à sua frente (8 cm).",
            "Estende os braços em direção a um objeto à sua frente e o apanha.",
            "Alcança um objeto preferido.",
            "Coloca objetos na boca.",
            "Eleva a cabeça e o tronco apoiando-se nos braços, ao estar deitado de barriga para baixo.",
            "Levanta a cabeça e o tronco apoiando-se em um só braço.",
            "Toca e explora objetos com a boca.",
            "Em decúbito ventral (de bruços), vira de lado e mantém esta posição ½ das vezes.",
            "Em decúbito ventral, vira de costas.",
            "Em decúbito ventral, move-se para frente o equivalente à sua altura.",
            "Em decúbito dorsal (de costas), rola para o lado.",
            "Em decúbito dorsal, vira de barriga para baixo.",
            "Faz esforço para sentar-se, segurando nos dedos do adulto.",
            "Vira a cabeça com facilidade quando o corpo está apoiado.",
            "Mantém-se sentado por 2 minutos.",
            "Solta um objeto para apanhar outro.",
            "Apanha e deixa cair um objeto propositalmente.",
            "Fica em pé com o máximo de apoio.",
            "Estando em pé com apoio, pula para cima e para baixo.",
            "Engatinha para apanhar um objeto (distante à sua altura).",
            "Senta-se apoiando-se sozinho.",
            "Estando sentado, vira de gatinhas.",
            "Estando em decúbito ventral, consegue sentar-se.",
            "Senta-se sem o apoio das mãos.",
            "Atira objetos ao acaso.",
            "Balança para frente e para trás quando de gatinhas.",
            "Transfere objetos de uma mão para outra quando sentado.",
            "Retém em uma das mãos 2 cubos de 2,5 cm.",
            "Fica de joelhos.",
            "Fica em pé, apoiando-se em algo.",
            "Usa preensão de pinça para pegar objetos.",
            "Engatinha.",
            "Estando de gatinhas, estende uma das mãos para o alto.",
            "Fica em pé com o mínimo de apoio.",
            "Lambe a comida ao redor da boca.",
            "Mantém-se em pé sozinho por um minuto.",
            "Derruba um objeto que está dentro de um recipiente.",
            "Vira várias páginas de um livro ao mesmo tempo.",
            "Escava com uma colher ou pá",
            "Coloca pequenos objetos dentro do recipiente. ",
            "Estando de pé, abaixa-se e senta. ",
            "Bate palmas.",
            "Anda com um mínimo de apoio. ",
            "Dá alguns passos sem apoio. "
        ]
    },
    '1 a 2 ano': {
        'Socialização': [
            "Imita um adulto em uma tarefa simples",
            "Brinca ao lado de outra criança, cada uma realizando tarefas diferentes",
            "Toma parte em uma brincadeira com outra criança por 2 a 5 minutos",
            "Aceita a ausência dos pais, embora possa reclamar",
            "Explora ativamente seu meio ambiente",
            "Realiza atividade manipulativa com outra pessoa",
            "Abraça e carrega uma boneca ou brinquedo macio",
            "Repete ações que produzem risos e atenção",
            "Dá um livro para que um adulto o leia ou para que ambos o compartilhem",
            "Puxa uma pessoa a mostrar-lhe algo",
            "Retira a mão ou diz 'não' quando está próximo de um objeto não permitido e alguém o lembra disto",
            "Quando colocado em sua cadeira ou trocador espera ser atendido",
            "Brinca com 2 ou 3 crianças da sua idade",
            "Compartilha um objeto ou alimento com outra criança",
            "Cumprimenta colegas ou adultos quando lembrado"
        ],
        "Cognição": [
            "Retira 6 objetos de um recipiente, um por vez",
            "Aponta para uma parte do corpo",
            "Empilha 3 blocos, dada a ordem",
            "Emparelha objetos semelhantes",
            "Faz rabiscos no papel",
            "Aponta para si quando perguntam 'Cadê o Fulano?'",
            "Coloca 5 pinos redondos, dada a ordem",
            "Emparelha objetos com a figura do mesmo nome",
            "Aponta para a figura nomeada",
            "Vira as páginas de um livro (2/3 por vez) para encontrar a figura nomeada"
        ],
        'Auto Cuidado': [
            "Come com colher de modo independente",
            "Segura a caneca com uma só mão e bebe",
            "Coloca a mão na água e dá tapinhas no rosto com as mãos molhadas, imitando alguém",
            "Senta-se em um piniquinho ou sanitário infantil por 5 min",
            "Coloca um chapéu na cabeça e o remove",
            "Tira as meias",
            "Empurra os braços pelas mangas e os pés pelas pernas da calça",
            "Tira os sapatos quando os cordões estiverem desamarrados",
            "Tira o casaco quando desabotoado",
            "Tira a calça quando desabotoada",
            "Puxa um fecho grande para cima e para baixo",
            "Utiliza palavras ou gestos indicando necessidade de ir ao banheiro",
        ],
        'Language': [
            "Diz 5 palavras diferentes",
            "Pede 'mais'",
            "Diz 'acabou'",
            "Obedece a 3 ordens diferentes que não são acompanhadas de gestos indicativos",
            "Consegue 'dar' ou 'mostrar' quando solicitado",
            "Aponta para 12 objetos quando nomeados",
            "Aponta para 3 a 5 figuras em um livro",
            "Aponta para 3 partes de seu próprio corpo",
            "Diz seu nome ou apelido quando solicitado",
            "Responde à pergunta 'O que é isto?'",
            "Combina palavras e gestos para expressar desejos",
            "Nomeia 5 membros da família, incluindo animais",
            "Nomeia 4 brinquedos",
            "Produz sons de animais, ou os nomeia pelo som",
            "Pede alimentos conhecidos pelo nome, quando mostrados",
            "Faz perguntas variando a entonação da voz.",
            "Nomeia 3 partes do corpo em uma boneca ou outra pessoa.",
            "Responde a perguntas de sim / não."
        ],
        "Desenvolvimento Motor": [
            "Sobe escadas engatinhando",
            "Coloca-se em pé, estando sentado",
            "Rola uma bola imitando um adulto",
            "Sobe em uma cadeira de adulto, vira-se e senta",
            "Coloca 4 aros em uma pequena estaca",
            "Retira pinos de 2,5 cm de uma prancha ou tabuleiro",
            "Encaixa pinos de 2,5 cm em uma prancha de encaixe",
            "Constrói uma torre de 3 blocos",
            "Faz traços no papel com lápis ou lápis de cera",
            "Anda sozinho",
            "Desce escadas sentado, colocando primeiro os pés",
            "Senta-se em uma cadeirinha",
            "Agacha-se e volta a ficar em pé",
            "Empurra e puxa brinquedos ao andar",
            "Usa cadeira ou cavalo de balanço",
            "Sobe escadas com ajuda",
            "Dobra o corpo sem cair para apanhar objetos no chão",
            "Imita um movimento circular"
        ]
    },
    '2 a 3 ano': {},
    '3 a 4 ano': {},
    '4 a 5 ano': {},
    '5 a 6 ano': {}
}
